#!/bin/sh
exec 2>&1

export SHINIT_USER=codelabs

[ -r ./conf ] && . ./conf

shinit

# This is a strange thing to do, but this service should generally
# speaking only ever run once in the life of a machine.
rm -f /var/service/shinit
